"""
model_service.py

Serves the *actual* trained-model results (not mock numbers) for the
Model Training & Performance Center.

The metrics below are transcribed directly from
ModelTraining/reports/*.txt (copied into backend/model_reports/) so
they always match what the training scripts produced. The raw report
text is still exposed via `raw_report` for anyone who wants the full
detail, and the plot PNGs already generated by the training scripts
are served as static files from backend/model_plots/.
"""

import os

import config

MODELS = {
    "Random Forest": {
        "name": "Random Forest",
        "type": "Supervised Ensemble (Bagging)",
        "purpose": "Satellite health-state classification",
        "target": "Health Prediction",
        "train_samples": 7200,
        "test_samples": 1800,
        "features": 7,
        "hyperparameters": {"n_estimators": "400", "max_depth": "10", "min_samples_leaf": "3", "class_weight": "balanced"},
        "accuracy": 0.762,
        "precision": 0.760,
        "recall": 0.762,
        "f1": 0.761,
        "roc_auc": 0.8121,
        "confusion_matrix": {"labels": ["Unhealthy", "Healthy"], "matrix": [[453, 227], [202, 918]]},
        "feature_importance": {
            "battery_voltage": 0.1919, "attitude_control_error": 0.1839, "thermal_control_status": 0.1837,
            "solar_panel_temperature": 0.1826, "time_since_launch": 0.0987, "data_transmission_rate": 0.0904,
            "orbital_altitude": 0.0687,
        },
        "plots": ["rf_confusion_matrix.png", "rf_roc_curve.png", "rf_feature_importance.png"],
        "deployment_status": "Active",
        "model_file": "model_rf.joblib",
        "is_best_health_model": True,
    },
    "XGBoost": {
        "name": "XGBoost",
        "type": "Supervised Ensemble (Gradient Boosting)",
        "purpose": "Satellite health-state classification",
        "target": "Health Prediction",
        "train_samples": 7200,
        "test_samples": 1800,
        "features": 7,
        "hyperparameters": {"learning_rate": "0.05", "max_depth": "3", "n_estimators": "200"},
        "accuracy": 0.751,
        "precision": 0.753,
        "recall": 0.751,
        "f1": 0.751,
        "roc_auc": 0.8102,
        "confusion_matrix": {"labels": ["Unhealthy", "Healthy"], "matrix": [[469, 211], [238, 882]]},
        "feature_importance": {
            "thermal_control_status": 0.4118, "attitude_control_error": 0.1498, "solar_panel_temperature": 0.1479,
            "battery_voltage": 0.1458, "data_transmission_rate": 0.0615, "time_since_launch": 0.0577,
            "orbital_altitude": 0.0256,
        },
        "plots": ["xgb_confusion_matrix.png", "xgb_roc_curve.png", "xgb_feature_importance.png"],
        "deployment_status": "Trained (not deployed)",
        "model_file": "model_xgboost.joblib",
        "is_best_health_model": False,
    },
    "SVM": {
        "name": "SVM",
        "type": "Supervised Kernel Classifier (RBF)",
        "purpose": "Satellite health-state classification",
        "target": "Health Prediction",
        "train_samples": 7200,
        "test_samples": 1800,
        "features": 7,
        "hyperparameters": {"C": "5", "gamma": "0.01", "kernel": "rbf"},
        "accuracy": 0.727,
        "precision": 0.739,
        "recall": 0.727,
        "f1": 0.730,
        "roc_auc": 0.7897,
        "confusion_matrix": {"labels": ["Unhealthy", "Healthy"], "matrix": [[491, 189], [303, 817]]},
        "feature_importance": {},
        "plots": ["svm_confusion_matrix.png", "svm_roc_curve.png"],
        "deployment_status": "Trained (not deployed)",
        "model_file": "model_svm.joblib",
        "is_best_health_model": False,
    },
    "Isolation Forest": {
        "name": "Isolation Forest",
        "type": "Unsupervised Anomaly Detector",
        "purpose": "Telemetry anomaly detection",
        "target": "Anomaly Detection",
        "train_samples": 4480,
        "test_samples": 9000,
        "features": 7,
        "hyperparameters": {"n_estimators": "300", "contamination": "0.378"},
        "accuracy": 0.653,
        "precision": 0.684,
        "recall": 0.653,
        "f1": 0.658,
        "roc_auc": 0.7244,
        "confusion_matrix": {"labels": ["Unhealthy", "Healthy"], "matrix": [[2410, 990], [2137, 3463]]},
        "feature_importance": {},
        "plots": ["isoforest_score_distribution.png", "isoforest_roc_curve.png", "isoforest_confusion_matrix.png"],
        "deployment_status": "Active",
        "model_file": "model_isolation_forest.joblib",
        "is_best_anomaly_model": True,
        "notes": "Trained unsupervised on healthy rows only (4,480). True labels used only for evaluation on the full 9,000-row dataset, never seen during training.",
    },
    "One-Class SVM": {
        "name": "One-Class SVM",
        "type": "Unsupervised Novelty Detector",
        "purpose": "Telemetry anomaly detection",
        "target": "Anomaly Detection",
        "train_samples": 4480,
        "test_samples": 9000,
        "features": 7,
        "hyperparameters": {"nu": "0.378", "kernel": "rbf"},
        "accuracy": 0.632,
        "precision": 0.658,
        "recall": 0.632,
        "f1": 0.638,
        "roc_auc": 0.6781,
        "confusion_matrix": {"labels": ["Unhealthy", "Healthy"], "matrix": [[2230, 1170], [2141, 3459]]},
        "feature_importance": {},
        "plots": ["ocsvm_score_distribution.png", "ocsvm_roc_curve.png", "ocsvm_confusion_matrix.png"],
        "deployment_status": "Trained (not deployed)",
        "model_file": "model_oneclass_svm.joblib",
        "is_best_anomaly_model": False,
    },
    "Autoencoder": {
        "name": "Autoencoder",
        "type": "Reconstruction-Error Anomaly Detector (MLPRegressor bottleneck)",
        "purpose": "Telemetry anomaly detection",
        "target": "Anomaly Detection",
        "train_samples": 4480,
        "test_samples": 9000,
        "features": 7,
        "hyperparameters": {"architecture": "7-4-2-4-7", "iterations": "199", "final_training_loss": "0.27313"},
        "accuracy": 0.646,
        "precision": 0.646,
        "recall": 0.646,
        "f1": 0.646,
        "roc_auc": 0.6705,
        "confusion_matrix": {"labels": ["Unhealthy", "Healthy"], "matrix": [[1806, 1594], [1594, 4006]]},
        "feature_importance": {},
        "plots": ["autoencoder_loss_curve.png", "autoencoder_error_distribution.png", "autoencoder_roc_curve.png", "autoencoder_confusion_matrix.png"],
        "deployment_status": "Trained (not deployed)",
        "model_file": "model_autoencoder.joblib",
        "is_best_anomaly_model": False,
        "notes": "Reconstruction-error threshold set at the 37.8th percentile (top 37.8% flagged anomalous), matching the dataset's known unhealthy fraction.",
    },
}

BEST_HEALTH_MODEL = "Random Forest"
BEST_ANOMALY_MODEL = "Isolation Forest"


def list_models():
    return list(MODELS.values())


def get_model(name):
    model = MODELS.get(name)
    if not model:
        return None
    result = dict(model)
    report_path = config.MODEL_REPORT_PATHS.get(name)
    if report_path and os.path.exists(report_path):
        with open(report_path, "r", encoding="utf-8", errors="replace") as f:
            result["raw_report"] = f.read()
    return result


def best_models():
    return {
        "health_prediction": BEST_HEALTH_MODEL,
        "anomaly_detection": BEST_ANOMALY_MODEL,
    }
